# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadDialog(object):
    def setupUi(self, LoadDialog):
        LoadDialog.setObjectName("LoadDialog")
        LoadDialog.resize(590, 403)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(LoadDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(LoadDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(LoadDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.strategies_textEdit = QtWidgets.QPlainTextEdit(LoadDialog)
        self.strategies_textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.strategies_textEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.strategies_textEdit.setReadOnly(True)
        self.strategies_textEdit.setPlainText("")
        self.strategies_textEdit.setObjectName("strategies_textEdit")
        self.horizontalLayout.addWidget(self.strategies_textEdit)
        self.choose_strategies_button = QtWidgets.QPushButton(LoadDialog)
        self.choose_strategies_button.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_strategies_button.setObjectName("choose_strategies_button")
        self.horizontalLayout.addWidget(self.choose_strategies_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(LoadDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prehistory_textEdit = QtWidgets.QPlainTextEdit(LoadDialog)
        self.prehistory_textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.prehistory_textEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.prehistory_textEdit.setReadOnly(True)
        self.prehistory_textEdit.setPlainText("")
        self.prehistory_textEdit.setObjectName("prehistory_textEdit")
        self.horizontalLayout_2.addWidget(self.prehistory_textEdit)
        self.choose_prehistory_button = QtWidgets.QPushButton(LoadDialog)
        self.choose_prehistory_button.setMinimumSize(QtCore.QSize(0, 40))
        self.choose_prehistory_button.setObjectName("choose_prehistory_button")
        self.horizontalLayout_2.addWidget(self.choose_prehistory_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cancel_button = QtWidgets.QPushButton(LoadDialog)
        self.cancel_button.setMinimumSize(QtCore.QSize(160, 40))
        self.cancel_button.setMaximumSize(QtCore.QSize(160, 16777215))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_3.addWidget(self.cancel_button)
        self.run_button = QtWidgets.QPushButton(LoadDialog)
        self.run_button.setMinimumSize(QtCore.QSize(160, 40))
        self.run_button.setMaximumSize(QtCore.QSize(160, 16777215))
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_3.addWidget(self.run_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(LoadDialog)
        QtCore.QMetaObject.connectSlotsByName(LoadDialog)

    def retranslateUi(self, LoadDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadDialog.setWindowTitle(_translate("LoadDialog", "Load data"))
        self.label_3.setText(_translate("LoadDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Load data</span></p></body></html>"))
        self.label.setText(_translate("LoadDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">STRATEGIES</span></p></body></html>"))
        self.choose_strategies_button.setText(_translate("LoadDialog", "Choose file"))
        self.label_2.setText(_translate("LoadDialog", "<html><head/><body><p><span style=\" font-size:14pt;\">PREHISTORY</span></p></body></html>"))
        self.choose_prehistory_button.setText(_translate("LoadDialog", "Choose file"))
        self.cancel_button.setText(_translate("LoadDialog", "Cancel"))
        self.run_button.setText(_translate("LoadDialog", "RUN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadDialog = QtWidgets.QDialog()
    ui = Ui_LoadDialog()
    ui.setupUi(LoadDialog)
    LoadDialog.show()
    sys.exit(app.exec_())
